version: '3.3'
services:
  influxdb:
    container_name: th3essentials-influxdb
    image: 'influxdb:2.6.1'
    ports:
        - ${INFLUXDB_PORT}:8086
    volumes:
        - ${INFLUXDB_DATA}:/var/lib/influxdb2
        - ${INFLUXDB_CONFIG}:/etc/influxdb2
  grafana:
    container_name: th3essentials-grafana
    image: grafana/grafana:9.3.6
# add this and make sure that your default user has write acces to the grafana folder
    user: "1000"
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - ${GRAFANA_DATA}:/var/lib/grafana

# if you wanna use it with pterodactyl uncomment to connect it to the pterodactyl network (so it can push data to influx from the vs server)
#networks:
#  default:
#    external: true
#    name: pterodactyl_nw
